# Server
server.port=8081

# ======================
# DATASOURCE (SQLite)
# ======================
spring.datasource.url=jdbc:sqlite:movies.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.hikari.maximum-pool-size=1

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ======================
# TMDB
# ======================
tmdb.base.url=https://api.themoviedb.org/3
tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlM2I1YTEyODhhM2Q1ZTNmZDU0ODhjZjEyYzU5M2VmZiIsIm5iZiI6MTc2Nzc5ODUyNi41MjQsInN1YiI6IjY5NWU3NmZlNzY1NTBmYjhlODNmNWVhNCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.aZ-DUlAT-x_o0SQrIAZj9gA10Nid2osNTrGR0PLwaBo
